apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: reliability-platform
  namespace: reliability-platform
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: reliability-platform
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
